#Day 6: Missing Values (NaN)
Pandas Course

In [1]:
import pandas as pd
import numpy as np

data = {
    "name": ["Ahmed", "Sara", "Omar", "Lina"],
    "math": [90, np.nan, 85, 70],
    "english": [88, 92, np.nan, 75],
}
df = pd.DataFrame(data)
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN
3   Lina  70.0     75.0

In [3]:
df.isna().sum()

name       0
math       1
english    1
dtype: int64

In [14]:
data = {
    "name": ["  ahmed  ", "Sara", "Omar", "lina"],
    "city": ["cairo", "Giza", "alex", "Cairo"]
}
df = pd.DataFrame(data)
df

        name   city
0    ahmed    cairo
1       Sara   Giza
2       Omar   alex
3       lina  Cairo

In [12]:
df["name"].str.strip()

0    ahmed
1     Sara
2     Omar
3     lina
Name: name, dtype: str

In [15]:
df["name"].str.lower()

0      ahmed
1         sara
2         omar
3         lina
Name: name, dtype: str

In [16]:
df["name"].str.upper()

0      AHMED
1         SARA
2         OMAR
3         LINA
Name: name, dtype: str

In [17]:
df["name"].str.contains("a")

0    True
1    True
2    True
3    True
Name: name, dtype: bool

In [18]:
df["city"] = df["city"].str.lower()
df

        name   city
0    ahmed    cairo
1       Sara   giza
2       Omar   alex
3       lina  cairo

In [19]:
df["name"] = df["name"].str.strip().str.lower()
df

    name   city
0  ahmed  cairo
1   sara   giza
2   omar   alex
3   lina  cairo

#Day 8: Filtering & Conditions in Pandas

In [1]:
import pandas as pd
data = {
    "name": ["Ahmed", "Sara", "Omar", "Lina"],
    "math": [90, 85, 85, 70],
    "english": [88, 92, 85, 75],
}
df = pd.DataFrame(data)
df

    name  math  english
0  Ahmed    90       88
1   Sara    85       92
2   Omar    85       85
3   Lina    70       75

In [2]:
df[df["math"] > 80]

    name  math  english
0  Ahmed    90       88
1   Sara    85       92
2   Omar    85       85

In [3]:
df[df["name"] =="Ahmed"]

    name  math  english
0  Ahmed    90       88

In [4]:
df[(df["math"] > 80) & (df["english"] > 85)]

    name  math  english
0  Ahmed    90       88
1   Sara    85       92

In [5]:
df[(df["math"] > 70) | (df["english"] > 80)]

    name  math  english
0  Ahmed    90       88
1   Sara    85       92
2   Omar    85       85

In [6]:
df[df["math"].isin(["Ahmed", "Lina"])]

Empty DataFrame
Columns: [name, math, english]
Index: []

In [7]:
df[df["math"] > 70].sort_values(by="math",ascending=False)

    name  math  english
0  Ahmed    90       88
1   Sara    85       92
2   Omar    85       85

In [8]:
df[df["english"] >=80]

    name  math  english
0  Ahmed    90       88
1   Sara    85       92
2   Omar    85       85

In [13]:

df[df["english"] >=80].sort_values(by="english",ascending=False)

    name  math  english
1   Sara    85       92
0  Ahmed    90       88
2   Omar    85       85

In [14]:
df.sort_values(by="english",ascending=False)

    name  math  english
1   Sara    85       92
0  Ahmed    90       88
2   Omar    85       85
3   Lina    70       75

#Day 9: GroupBy

In [17]:
import pandas as pd
data = {
    "student": ["Ahmed", "Sara", "Omar", "Lina", "Mona"],
    "department": ["CS", "IT", "CS", "IT", "CS"],
    "score": [90, 85, 88, 92, 95]
}
df = pd.DataFrame(data)
df

  student department  score
0   Ahmed         CS     90
1    Sara         IT     85
2    Omar         CS     88
3    Lina         IT     92
4    Mona         CS     95

In [18]:
df.groupby("department")["score"].mean()

department
CS    91.0
IT    88.5
Name: score, dtype: float64

In [19]:
df.groupby("department")["score"].agg(['mean', 'max', 'min','count'])

            mean  max  min  count
department
CS          91.0   95   88      3
IT          88.5   92   85      2

In [20]:
df.groupby(["department", "student"])["score"].mean()

department  student
CS          Ahmed      90.0
            Mona       95.0
            Omar       88.0
IT          Lina       92.0
            Sara       85.0
Name: score, dtype: float64

In [22]:
result = df.groupby("department")["score"].mean().reset_index()
result

  department  score
0         CS   91.0
1         IT   88.5

Day 10: Handling Missing Data(NaN) in pandas

In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["Ahmed", "Sara", "Omar"],
    "math": [90, np.nan, 85],
    "english": [88, 92, np.nan],
})
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN

In [2]:
df.isna().sum()

name       0
math       1
english    1
dtype: int64

In [17]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN

remove rows that have NaN = keep the columns that have not NaN

In [18]:
df.dropna(axis=0)

    name  math  english
0  Ahmed  90.0     88.0

In [16]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN

In [5]:
df.dropna(axis=1)

    name
0  Ahmed
1   Sara
2   Omar

In [6]:
df.fillna(0)

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   0.0     92.0
2   Omar  85.0      0.0

In [8]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN

In [7]:
df["math"].fillna(df["math"].mean())

0    90.0
1    87.5
2    85.0
Name: math, dtype: float64

In [10]:
df.fillna(df.mean(numeric_only=True))

    name  math  english
0  Ahmed  90.0     88.0
1   Sara  87.5     92.0
2   Omar  85.0     90.0

calculate the mean of numerical columns only

In [20]:
clean_df = df.fillna(df.mean(numeric_only=True))
clean_df.mean(numeric_only=True)

math       87.5
english    90.0
dtype: float64

Day 11: GroupBy & Aggregation

In [4]:
import pandas as pd

data = {
    "department": ["IT", "HR", "IT", "HR", "Sales","Sales"],
    "employee": ["Ahmed", "Sara", "Omar", "Lina", "Mona", "Ali"],
    "salary": [5000, 4500, 5200, 4800, 5500, 5300]
}
df = pd.DataFrame(data)
df

  department employee  salary
0         IT    Ahmed    5000
1         HR     Sara    4500
2         IT     Omar    5200
3         HR     Lina    4800
4      Sales     Mona    5500
5      Sales      Ali    5300

In [13]:
df.groupby("department")["salary"].mean().sort_values(ascending=False)

department
Sales    5400.0
IT       5100.0
HR       4650.0
Name: salary, dtype: float64

In [11]:
result = df.groupby("department")["salary"].mean().reset_index()
result

  department  salary
0         HR  4650.0
1         IT  5100.0
2      Sales  5400.0

In [10]:
df.groupby("department").agg({"salary":["mean", "sum"], "employee":"count"})

            salary        employee
              mean    sum    count
department
HR          4650.0   9300        2
IT          5100.0  10200        2
Sales       5400.0  10800        2

In [9]:
df.groupby(["department","employee"]).agg(["mean", "sum", "max", "min"])

                     salary
                       mean   sum   max   min
department employee
HR         Lina      4800.0  4800  4800  4800
           Sara      4500.0  4500  4500  4500
IT         Ahmed     5000.0  5000  5000  5000
           Omar      5200.0  5200  5200  5200
Sales      Ali       5300.0  5300  5300  5300
           Mona      5500.0  5500  5500  5500

In [5]:
df.groupby("department")["salary"].mean()

department
HR       4650.0
IT       5100.0
Sales    5400.0
Name: salary, dtype: float64

In [6]:
df.groupby("department")["salary"].agg(["mean", "sum", "max", "min"])

              mean    sum   max   min
department
HR          4650.0   9300  4800  4500
IT          5100.0  10200  5200  5000
Sales       5400.0  10800  5500  5300

Day 12: Merge & Join

In [14]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Ahmed", "Sara", "Omar", "Lina"]
})
orders = pd.DataFrame({
    "customer_id": [1, 1, 2, 3],
    "order_amount": [500, 300, 700, 200]
})
customers

   customer_id   name
0            1  Ahmed
1            2   Sara
2            3   Omar
3            4   Lina

In [15]:
orders

   customer_id  order_amount
0            1           500
1            1           300
2            2           700
3            3           200

In [16]:
merged = pd.merge(customers, orders, on="customer_id")
merged

   customer_id   name  order_amount
0            1  Ahmed           500
1            1  Ahmed           300
2            2   Sara           700
3            3   Omar           200

In [20]:
left_join = pd.merge(customers, orders, on="customer_id", how="left")
left_join

   customer_id   name  order_amount
0            1  Ahmed         500.0
1            1  Ahmed         300.0
2            2   Sara         700.0
3            3   Omar         200.0
4            4   Lina           NaN

In [22]:
right_join = pd.merge(customers, orders, on="customer_id", how="right")
right_join

   customer_id   name  order_amount
0            1  Ahmed           500
1            1  Ahmed           300
2            2   Sara           700
3            3   Omar           200

In [23]:
outer_join = pd.merge(customers, orders, on="customer_id", how="outer")
outer_join

   customer_id   name  order_amount
0            1  Ahmed         500.0
1            1  Ahmed         300.0
2            2   Sara         700.0
3            3   Omar         200.0
4            4   Lina           NaN

In [24]:
merged.groupby("name")["order_amount"].sum()

name
Ahmed    800
Omar     200
Sara     700
Name: order_amount, dtype: int64

Day 13: Handling Missing Data

In [26]:
import pandas as pd
import numpy as np

data = {
    "name": ["Ahmed", "Sara", "Omar", "Lina"],
    "math": [90, np.nan, 85, 60],
    "english": [88, 92, np.nan, 80],
}
df = pd.DataFrame(data)
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN
3   Lina  60.0     80.0

In [27]:
df.isna()

    name   math  english
0  False  False    False
1  False   True    False
2  False  False     True
3  False  False    False

In [28]:
df.isna().sum()

name       0
math       1
english    1
dtype: int64

In [30]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN
3   Lina  60.0     80.0

In [29]:
df.dropna()

    name  math  english
0  Ahmed  90.0     88.0
3   Lina  60.0     80.0

In [32]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN
3   Lina  60.0     80.0

In [31]:
df.dropna(subset=["math"])

    name  math  english
0  Ahmed  90.0     88.0
2   Omar  85.0      NaN
3   Lina  60.0     80.0

In [33]:
df.fillna(0)

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   0.0     92.0
2   Omar  85.0      0.0
3   Lina  60.0     80.0

In [34]:
df["math"].fillna(df["math"].mean())

0    90.000000
1    78.333333
2    85.000000
3    60.000000
Name: math, dtype: float64

In [35]:
df.fillna(df.mean(numeric_only=True))

    name       math    english
0  Ahmed  90.000000  88.000000
1   Sara  78.333333  92.000000
2   Omar  85.000000  86.666667
3   Lina  60.000000  80.000000

In [42]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN
3   Lina  60.0     80.0

In [40]:
df.ffill()

    name  math  english
0  Ahmed  90.0     88.0
1   Sara  90.0     92.0
2   Omar  85.0     92.0
3   Lina  60.0     80.0

In [43]:
df

    name  math  english
0  Ahmed  90.0     88.0
1   Sara   NaN     92.0
2   Omar  85.0      NaN
3   Lina  60.0     80.0

In [41]:
df.bfill()

    name  math  english
0  Ahmed  90.0     88.0
1   Sara  85.0     92.0
2   Omar  85.0     80.0
3   Lina  60.0     80.0